name: ci-cluster-api-provider-aws-config
on:
  pull_request:
    paths:
      - '*/**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - name: binaries
        run: make binaries
      - name: docker-build
        run: podman build -f stolostron/Dockerfile.stolostron .
      - name: test
        run: make test
